# Project Information
site_name: CTF Wiki
site_description: CTF Wiki
site_author: 40huo
site_url: https://40huo.github.io/ctf-wiki/

# Repository
repo_name: 'ctf-wiki/ctf-wiki'
repo_url: 'https://github.com/40huo/ctf-wiki'
edit_uri: 'blob/master/docs/'

# Copyright
copyright: 'Copyright &copy; 2016 - 2018 CTF Wiki Team'

# Contents
pages:
  - Introduction:
    - Getting Started: index.md
    - CTF 历史: introduction/history.md
    - CTF 竞赛模式简介: introduction/mode.md
    - CTF 竞赛内容: introduction/content.md
    - 线下攻防经验小结: introduction/experience.md
    - CGC 超级挑战赛: introduction/cgc.md
    - 学习资源: introduction/resources.md
  - Crypto:
    - 密码学简介: crypto/introduction.md
    - 古典密码:
      - 古典密码简介: crypto/classical/introduction.md
      - 单表代换加密: crypto/classical/monoalphabetic.md
      - 多表代换加密: crypto/classical/polyalphabetic.md
      - 其他类型加密: crypto/classical/others.md
      - 总结: crypto/classical/summary.md
  - Pwn:
    - StackOverflow 栈溢出:
      - 栈介绍: pwn/stackoverflow/stack_intro.md
      - 栈溢出原理: pwn/stackoverflow/stackoverflow_basic.md
      - 基本 ROP: pwn/stackoverflow/basic_rop.md
      - 花式栈溢出技巧: pwn/stackoverflow/others.md
      - 中级 ROP: pwn/stackoverflow/medium_rop.md
      - 高级 ROP: pwn/stackoverflow/advanced_rop.md
    - 格式化字符串:
      - 格式化字符串漏洞原理介绍: pwn/fmtstr/fmtstr_intro.md
      - 格式化字符串漏洞利用: pwn/fmtstr/fmtstr_exploit.md
      - 格式化字符串漏洞例子: pwn/fmtstr/fmtstr_example.md
      - 格式化字符串漏洞检测: pwn/fmtstr/fmtstr_detect.md
    - 堆利用:
      - 堆概述: pwn/heap/heap_overview.md
      - 堆相关数据结构: pwn/heap/heap_structure.md
      - 深入理解堆的实现: pwn/heap/heap_implementation_details.md
      - 堆溢出: pwn/heap/heapoverflow_basic.md
      - 堆中的 Off-By-One: pwn/heap/off_by_one.md
      - Unlink: pwn/heap/unlink.md
      - Use After Free: pwn/heap/use_after_free.md
      - Fastbin Attack: pwn/heap/fastbin_attack.md
      - Chunk Extend / Shrink: pwn/heap/chunk_extend_shrink.md
      - House Of Einherjar: pwn/heap/house_of_einherjar.md
      - House of Lore: pwn/heap/house_of_lore.md
      - House Of Force: pwn/heap/house_of_force.md
      - Unsorted Bin Attack: pwn/heap/unsorted_bin_attack.md
  - Executable:
    - ELF 文件:
      - ELF文件基本结构: executable/elf/elf_structure.md
      - 程序加载: executable/elf/program_loading.md
      - 程序链接: executable/elf/program_linking.md
      - 程序执行流程: executable/elf/running_overview.md

# Theme
theme:
  name: 'material'
  language: 'zh'
  palette:
    primary: 'white'
    accent: 'red'
  logo:
    icon: 'school'
  feature:
    tabs: true
  font:
    text: 'Monda'
    code: 'Fira Mono'

# Customization
extra:
  search:
    language: 'jp'

extra_javascript:
  - 'static/js/extra.js'
  - 'https://cdn.bootcss.com/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML'

extra_css:
  - 'static/css/extra.css'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde